import type { Metadata } from "next";
import "./globals.css";
import MuiProvider from "@/lib/MuiProvider";
import FloatingContact from "@/components/FloatingContact";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className="bg-[url('https://images.unsplash.com/photo-1542744094-24638eff58bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1950&q=80'))] bg-cover bg-fixed bg-center"
      >
        <MuiProvider>{children}</MuiProvider>
        <FloatingContact />
      </body>
    </html>
  );
}
